package wci.message;

public enum  MessageType
{
    SOURCE_LINE, SYNTAX_ERROR,
    PARSE_SUMMARY, INTERPRETER_SUMMARY, COMPILER_SUMMARY,
    MISCELLANEOUS, TOKEN,
    ASSIGN, FETCH, BREAKPOINT, RUNTIME_ERROR,
    CALL, RETURN,
}
